# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from aruco_markers/Marker.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class Marker(genpy.Message):
  _md5sum = "92623b17f39559a329eab104a28d98d2"
  _type = "aruco_markers/Marker"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

# marker id
int16 id

# 3D space
geometry_msgs/Vector3 rvec
geometry_msgs/Vector3 tvec

# roll, pitch, yaw
geometry_msgs/Vector3 rpy

# pixel coordinates of corners (theta from Pose2D not used)
geometry_msgs/Pose2D[] pixel_corners

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta"""
  __slots__ = ['header','id','rvec','tvec','rpy','pixel_corners']
  _slot_types = ['std_msgs/Header','int16','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Pose2D[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,id,rvec,tvec,rpy,pixel_corners

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Marker, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.id is None:
        self.id = 0
      if self.rvec is None:
        self.rvec = geometry_msgs.msg.Vector3()
      if self.tvec is None:
        self.tvec = geometry_msgs.msg.Vector3()
      if self.rpy is None:
        self.rpy = geometry_msgs.msg.Vector3()
      if self.pixel_corners is None:
        self.pixel_corners = []
    else:
      self.header = std_msgs.msg.Header()
      self.id = 0
      self.rvec = geometry_msgs.msg.Vector3()
      self.tvec = geometry_msgs.msg.Vector3()
      self.rpy = geometry_msgs.msg.Vector3()
      self.pixel_corners = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_h9d().pack(_x.id, _x.rvec.x, _x.rvec.y, _x.rvec.z, _x.tvec.x, _x.tvec.y, _x.tvec.z, _x.rpy.x, _x.rpy.y, _x.rpy.z))
      length = len(self.pixel_corners)
      buff.write(_struct_I.pack(length))
      for val1 in self.pixel_corners:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.rvec is None:
        self.rvec = geometry_msgs.msg.Vector3()
      if self.tvec is None:
        self.tvec = geometry_msgs.msg.Vector3()
      if self.rpy is None:
        self.rpy = geometry_msgs.msg.Vector3()
      if self.pixel_corners is None:
        self.pixel_corners = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 74
      (_x.id, _x.rvec.x, _x.rvec.y, _x.rvec.z, _x.tvec.x, _x.tvec.y, _x.tvec.z, _x.rpy.x, _x.rpy.y, _x.rpy.z,) = _get_struct_h9d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pixel_corners = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.pixel_corners.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_h9d().pack(_x.id, _x.rvec.x, _x.rvec.y, _x.rvec.z, _x.tvec.x, _x.tvec.y, _x.tvec.z, _x.rpy.x, _x.rpy.y, _x.rpy.z))
      length = len(self.pixel_corners)
      buff.write(_struct_I.pack(length))
      for val1 in self.pixel_corners:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.rvec is None:
        self.rvec = geometry_msgs.msg.Vector3()
      if self.tvec is None:
        self.tvec = geometry_msgs.msg.Vector3()
      if self.rpy is None:
        self.rpy = geometry_msgs.msg.Vector3()
      if self.pixel_corners is None:
        self.pixel_corners = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 74
      (_x.id, _x.rvec.x, _x.rvec.y, _x.rvec.z, _x.tvec.x, _x.tvec.y, _x.tvec.z, _x.rpy.x, _x.rpy.y, _x.rpy.z,) = _get_struct_h9d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pixel_corners = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        self.pixel_corners.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_h9d = None
def _get_struct_h9d():
    global _struct_h9d
    if _struct_h9d is None:
        _struct_h9d = struct.Struct("<h9d")
    return _struct_h9d
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
