// Generated by gencpp from file aruco_markers/MarkerArray.msg
// DO NOT EDIT!


#ifndef ARUCO_MARKERS_MESSAGE_MARKERARRAY_H
#define ARUCO_MARKERS_MESSAGE_MARKERARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <aruco_markers/Marker.h>

namespace aruco_markers
{
template <class ContainerAllocator>
struct MarkerArray_
{
  typedef MarkerArray_<ContainerAllocator> Type;

  MarkerArray_()
    : markers()  {
    }
  MarkerArray_(const ContainerAllocator& _alloc)
    : markers(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::aruco_markers::Marker_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::aruco_markers::Marker_<ContainerAllocator> >::other >  _markers_type;
  _markers_type markers;





  typedef boost::shared_ptr< ::aruco_markers::MarkerArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aruco_markers::MarkerArray_<ContainerAllocator> const> ConstPtr;

}; // struct MarkerArray_

typedef ::aruco_markers::MarkerArray_<std::allocator<void> > MarkerArray;

typedef boost::shared_ptr< ::aruco_markers::MarkerArray > MarkerArrayPtr;
typedef boost::shared_ptr< ::aruco_markers::MarkerArray const> MarkerArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aruco_markers::MarkerArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aruco_markers::MarkerArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aruco_markers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'aruco_markers': ['/home/air/swarm_ws/src/aruco_markers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aruco_markers::MarkerArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco_markers::MarkerArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_markers::MarkerArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_markers::MarkerArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_markers::MarkerArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_markers::MarkerArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aruco_markers::MarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c83561ca1ae4ac98039651009b8168f1";
  }

  static const char* value(const ::aruco_markers::MarkerArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc83561ca1ae4ac98ULL;
  static const uint64_t static_value2 = 0x039651009b8168f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::aruco_markers::MarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aruco_markers/MarkerArray";
  }

  static const char* value(const ::aruco_markers::MarkerArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aruco_markers::MarkerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aruco_markers/Marker[] markers\n\
\n\
================================================================================\n\
MSG: aruco_markers/Marker\n\
std_msgs/Header header\n\
\n\
# marker id\n\
int16 id\n\
\n\
# 3D space\n\
geometry_msgs/Vector3 rvec\n\
geometry_msgs/Vector3 tvec\n\
\n\
# roll, pitch, yaw\n\
geometry_msgs/Vector3 rpy\n\
\n\
# pixel coordinates of corners (theta from Pose2D not used)\n\
geometry_msgs/Pose2D[] pixel_corners\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::aruco_markers::MarkerArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aruco_markers::MarkerArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.markers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MarkerArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aruco_markers::MarkerArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aruco_markers::MarkerArray_<ContainerAllocator>& v)
  {
    s << indent << "markers[]" << std::endl;
    for (size_t i = 0; i < v.markers.size(); ++i)
    {
      s << indent << "  markers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::aruco_markers::Marker_<ContainerAllocator> >::stream(s, indent + "    ", v.markers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARUCO_MARKERS_MESSAGE_MARKERARRAY_H
