// Generated by gencpp from file aruco_markers/Marker.msg
// DO NOT EDIT!


#ifndef ARUCO_MARKERS_MESSAGE_MARKER_H
#define ARUCO_MARKERS_MESSAGE_MARKER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Pose2D.h>

namespace aruco_markers
{
template <class ContainerAllocator>
struct Marker_
{
  typedef Marker_<ContainerAllocator> Type;

  Marker_()
    : header()
    , id(0)
    , rvec()
    , tvec()
    , rpy()
    , pixel_corners()  {
    }
  Marker_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , rvec(_alloc)
    , tvec(_alloc)
    , rpy(_alloc)
    , pixel_corners(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rvec_type;
  _rvec_type rvec;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _tvec_type;
  _tvec_type tvec;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _rpy_type;
  _rpy_type rpy;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _pixel_corners_type;
  _pixel_corners_type pixel_corners;





  typedef boost::shared_ptr< ::aruco_markers::Marker_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aruco_markers::Marker_<ContainerAllocator> const> ConstPtr;

}; // struct Marker_

typedef ::aruco_markers::Marker_<std::allocator<void> > Marker;

typedef boost::shared_ptr< ::aruco_markers::Marker > MarkerPtr;
typedef boost::shared_ptr< ::aruco_markers::Marker const> MarkerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aruco_markers::Marker_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aruco_markers::Marker_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aruco_markers

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'aruco_markers': ['/home/air/swarm_ws/src/aruco_markers/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aruco_markers::Marker_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco_markers::Marker_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_markers::Marker_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_markers::Marker_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_markers::Marker_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_markers::Marker_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aruco_markers::Marker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "92623b17f39559a329eab104a28d98d2";
  }

  static const char* value(const ::aruco_markers::Marker_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x92623b17f39559a3ULL;
  static const uint64_t static_value2 = 0x29eab104a28d98d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::aruco_markers::Marker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aruco_markers/Marker";
  }

  static const char* value(const ::aruco_markers::Marker_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aruco_markers::Marker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
# marker id\n\
int16 id\n\
\n\
# 3D space\n\
geometry_msgs/Vector3 rvec\n\
geometry_msgs/Vector3 tvec\n\
\n\
# roll, pitch, yaw\n\
geometry_msgs/Vector3 rpy\n\
\n\
# pixel coordinates of corners (theta from Pose2D not used)\n\
geometry_msgs/Pose2D[] pixel_corners\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::aruco_markers::Marker_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aruco_markers::Marker_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.rvec);
      stream.next(m.tvec);
      stream.next(m.rpy);
      stream.next(m.pixel_corners);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Marker_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aruco_markers::Marker_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aruco_markers::Marker_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "rvec: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rvec);
    s << indent << "tvec: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.tvec);
    s << indent << "rpy: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy);
    s << indent << "pixel_corners[]" << std::endl;
    for (size_t i = 0; i < v.pixel_corners.size(); ++i)
    {
      s << indent << "  pixel_corners[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.pixel_corners[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARUCO_MARKERS_MESSAGE_MARKER_H
