swarm_bot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Picked some random PIDs
  # Joint states
  # left_wheel_velocity_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: base_link_to_left_wheel
  #   # pid: {p: 100.0, i: 0.01, d: 10.0}
  #   pid: {p: 1.0, i: 0.01, d: 0.0}
  #
  # right_wheel_velocity_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: base_link_to_right_wheel
  #   # pid: {p: 100.0, i: 0.01, d: 10.0}
  #   pid: {p: 1.0, i: 0.01, d: 0.0}

  # left_wheel_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: base_link_to_left_wheel
  #   pid: {p: 100.0, i: 1.0, d: 0.0, i_clamp: 0.0}
  # right_wheel_velocity_controller:
  #   type: velocity_controllers/JointVelocityController
  #   joint: base_link_to_right_wheel
  #   pid: {p: 100.0, i: 1.0, d: 0.0, i_clamp: 0.0}

  left_wheel_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_to_left_wheel
  right_wheel_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_to_right_wheel

  # # Differential Drive Controller
  # swarm_base_controller:
  #   type: "diff_drive_controller/DiffDriveController"
  #   left_wheel: 'base_link_to_left_wheel'
  #   right_wheel: 'base_link_to_right_wheel'
  #   pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  #   twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  #   # Base frame_id
  #   base_frame_id: base_link
