swarm_bot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Picked some random PIDs
  # Joint states
  base_link_to_left_wheel_joint_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_left_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}

  base_link_to_right_wheel_joint_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_right_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
