swarm_bot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  left_wheel_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_to_left_wheel
  right_wheel_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_to_right_wheel
