<?xml version="1.0"?>
<robot name="blackhawk" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Values for different components of the robot-->
  <xacro:property name="wheel_separation" value="0.02"/>
  <xacro:property name="wheel_diameter" value="0.025"/>
  <xacro:property name="wheel_width" value="0.005"/>
  <xacro:property name="wheel_standoff" value="0.01"/>
  <xacro:property name="body_length" value="0.06"/>

  <xacro:include filename="$(find swarm_description)/urdf/macros.xacro"/>

  <!-- This is here to give RVIS a fixed global frame -->
  <link name="map">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>
  <joint name="map_to_base_link" type="fixed">
    <child link="base_link"/>
    <parent link="map"/>
  </joint>

  <!-- Main link for the robot_description -->
  <link name="base_link">
    <!-- visual -->
    <visual>
	    <origin rpy="0.0 0 0" xyz="0 0 ${body_length / 2}"/>
	    <xacro:body/>
    </visual>

    <!-- inertial & collision -->
    <collision>
	    <origin rpy="0.0 0 0" xyz="0 0 ${body_length / 2}"/>
        <xacro:body/>
      </collision>
    <inertial>
      <mass value="0.05"/>
      <inertia ixx="0.5" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="0.5"/>
    </inertial>
  </link>


  <!-- Wheel geometries -->
  <link name="left_wheel">
    <visual>
      <origin rpy="1.57079 0 0" xyz="${wheel_standoff} -${wheel_separation} 0"/>
      <xacro:wheel_geometry/>
    </visual>

    <collision>
	    <origin rpy="1.57079 0 0" xyz="${wheel_standoff} -${wheel_separation} 0"/>
      <xacro:wheel_geometry/>
    </collision>
  </link>

  <link name="right_wheel">
    <visual>
      <origin rpy="-1.57079 0 0" xyz="-${wheel_standoff} ${wheel_separation} 0"/>
      <xacro:wheel_geometry/>
    </visual>

    <collision>
	    <origin rpy="-1.57079 0 0" xyz="-${wheel_standoff} ${wheel_separation} 0"/>
      <xacro:wheel_geometry/>
    </collision>
  </link>

  <!-- wheel joints -->
  <joint name="base_link_to_left_wheel" type="fixed">
    <child link="left_wheel" />
    <parent link="base_link" />
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <joint name="base_link_to_right_wheel" type="fixed">
    <child link="right_wheel"/>
    <parent link="base_link"/>
    <axis xyz="0 1 0" rpy="0 0 0"/>
  </joint>

  <!-- Setting up transmissions for differential driving -->
  <xacro:mk_transmission joint="base_link_to_right_wheel"/>
  <xacro:mk_transmission joint="base_link_to_left_wheel"/>

  <!-- Using separate file to set up Gazebo properties and plugins -->
  <xacro:include filename="$(find swarm_description)/urdf/blackhawk_standalone.gazebo"/>

</robot>
