<?xml version="1.0"?>

<robot name="blackhawk" xmlns:xacro="http://ros.org/wiki/xacro">
  <link name="base_link">
    <!-- Body geometry macro -->
    <!-- <mesh filename="package://swarm_description/meshes/Blackhawk_resized.dae"/> -->
    <xacro:property name="body_length" value="0.06"/>
    <xacro:macro name="body">
      <geometry>
        <!--<cylinder length="${body_length}" radius="0.5" /> -->
        <mesh filename="package://swarm_description/meshes/Blackhawk_resized.dae"/>
      </geometry>
    </xacro:macro>

    <!-- Values for different components of the robot-->
    <xacro:property name="wheel_separation" value="0.02"/>
    <xacro:property name="wheel_diameter" value="0.025"/>
    <xacro:property name="wheel_width" value="0.005"/>
    <xacro:property name="wheel_standoff" value="0.01"/>

    <!-- visual -->
    <visual>
	    <origin rpy="0.0 0 0" xyz="0 0 ${body_length / 2}"/>
	    <xacro:body/>
    </visual>
    
    <!-- inertial & collision -->
    <collision>
	    <origin rpy="0.0 0 0" xyz="0 0 ${body_length / 2}"/>
        <xacro:body/>
      </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.5" ixy="0.0" ixz="0.0" iyy="0.5" iyz="0.0" izz="0.5"/>
    </inertial>
  </link>

  <!-- wheel joints -->
  <joint name="base_link_to_left_wheel" type="fixed">
    <child link="left_wheel" />
    <parent link="base_link" /> 
  </joint>

  <joint name="base_link_to_right_wheel" type="fixed">
	  <child link="right_wheel"/>
	  <parent link="base_link"/>
  </joint>

  <!-- Wheel geometry macro -->
  <xacro:macro name="wheel_geometry">
    <geometry>
	    <cylinder length="${wheel_width}" radius="${wheel_diameter / 2}"/>
    </geometry>
  </xacro:macro>

  <!-- Wheel geometries -->
  <link name="left_wheel">
    <visual>
      <origin rpy="1.57079 0 0" xyz="${wheel_standoff} -${wheel_separation} 0"/>
      <xacro:wheel_geometry/>
    </visual>

    <collision>
	    <origin rpy="1.57079 0 0" xyz="${wheel_standoff} -${wheel_separation} 0"/>
      <xacro:wheel_geometry/>
    </collision>
  </link>

  <link name="right_wheel">
    <visual>
      <origin rpy="-1.57079 0 0" xyz="-${wheel_standoff} ${wheel_separation} 0"/>
      <xacro:wheel_geometry/>
    </visual>

    <collision>
	    <origin rpy="-1.57079 0 0" xyz="-${wheel_standoff} ${wheel_separation} 0"/>
      <xacro:wheel_geometry/>
    </collision> 
  </link>
  
  <!-- Plugin to simulate driving motion -->  
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100</updateRate>
      <leftJoint>base_link_to_left_wheel</leftJoint>
      <rightJoint>base_link_to_right_wheel</rightJoint>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_diameter}</wheelDiameter>
      <wheelTorque>2</wheelTorque>
      <commandTopic>cmd_diff_vel</commandTopic>
      <broadcastTF>false</broadcastTF>
    </plugin>
  </gazebo>
</robot>
