<?xml version="1.0"?>

<robot name="blackhawk" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Body geometry macro -->
    <!-- <mesh filename="package://swarm_description/meshes/Blackhawk_resized.dae"/> -->
    <xacro:macro name="body">
      <geometry>
        <!--<cylinder length="${body_length}" radius="0.5" /> -->
        <mesh filename="package://swarm_description/meshes/Blackhawk_resized.dae"/>
      </geometry>
    </xacro:macro>

    <!-- Wheel geometry macro -->
    <xacro:macro name="wheel_geometry">
        <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_diameter / 2}"/>
        </geometry>
    </xacro:macro>

    <!-- transmission macros -->
    <xacro:macro name="mk_transmission" params="side">
        <transmission name="${side}_wheel_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="base_link_to_${side}_wheel">
                <hardwareInteface>EffortJointInterface</hardwareInteface>
            </joint>
            <actuator name="${side}_wheel_actuator">
                <mechanicalReduction>1</mechanicalReduction>
                <hardwareInteface>EffortJointInterface</hardwareInteface>
            </actuator>
        </transmission>
    </xacro:macro>

</robot>